### ISSUE TITLE
Categories not displaying Title

### ISSUE THREAD

**Issue by CKENT0369** [lyrasoft/quickicons#28]
I have an issue where the. 
![notitle](https://cloud.githubusercontent.com/assets/11754368/6963009/11908bce-d908-11e4-8478-b3f9ea0aaa88.PNG)
Also How do I remove those other icons in the above image, they are not in the list and wont leave.
![notitle2](https://cloud.githubusercontent.com/assets/11754368/6963010/11963808-d908-11e4-942d-a7b16e4f6cc8.PNG)

**Comment by asika32764** [comment]
I can't reproduce this issue, Could you try re-create a new category?

And which icons you want to remove? The Joomla update checking icons? These icons are inserted by plugins, you have to close these plugins to remove icons.

**Comment by CKENT0369** [comment]
Nope Still same issue. Its not pulling title at all. 
'<a data-toggle="tab" href="#tab-5521b7b1d9c18-32"></a>' That is how the code is coming up in FF. No text for the link???

**Comment by Laurentfrom47** [comment]
Hello, i have the same problem.

**Comment by Laurentfrom47** [comment]
I found the problem for me it was a conflict with the System - RokUpdater plugin i disable it and it is OK.

**Comment by asika32764** [comment]
Thank you for your information.
