### ISSUE TITLE
PHP7 incompatibility

### ISSUE THREAD

**Issue by ferino75** [lyrasoft/quickicons#33]
Hello,
after upgrade to Joomla 3.5 and PHP7:

Fatal error: Cannot use 'String' as class name as it is reserved in /home/sq016100/www_root/libraries/vendor/joomla/string/src/String.php on line 19

**Comment by asika32764** [comment]
Please try 2.0.5, thank you.
https://github.com/lyrasoft/quickicons/releases/tag/2.0.5

**Comment by ferino75** [comment]
Hello,
I installed v 2.0.5 with errors:

*Message*

Copy icons to: /home/do2922000/www_root/images/quickicons

Installation of the component was successful.

*Warning*

JInstaller: :Install: File does not exist
/home/do2922000/www_root/tmp/install_56f3ce1acda0e/quickicons-2.0.5/windwalker/resource

Library %s: Could not copy files from the source.





*Warning*:
copy(/home/do2922000/www_root/libraries/windwalker/config.dist.json):
failed to open stream: No such file or directory in
*/home/do2922000/www_root/tmp/install_56f3ce1acda0e/quickicons-2.0.5/windwalker/src/System/Installer/WindwalkerInstaller.php*
on line *56*


Then I see quickicons in administrator panel, but I cant go to Asikart
Quickicons in administrator menu:
An error has occurred.

0 Call to undefined function with()





2016-03-24 11:20 GMT+01:00 Simon Asika <notifications@github.com>:

> Closed #33 <https://github.com/lyrasoft/quickicons/issues/33>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lyrasoft/quickicons/issues/33#event-601545146>
>



-- 
FG
Gmail

**Comment by asika32764** [comment]
I can successfully install 2.0.5 in a new Joomla 3.5.0
![banners_and_alerts_ _joomla_350_-_administration_-_icons](https://cloud.githubusercontent.com/assets/1639206/14019487/fc479274-f20d-11e5-8f48-0217b2f3bd22.jpg)

It seems you miss the windwalker library files, do you check the file permissions?

Try directly install windwalker and re open AQI to test.
Download: https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.1/lib_windwalker_2.1.zip

**Comment by ferino75** [comment]
I install windwalker and now is OK.

Thank you.

2016-03-24 15:18 GMT+01:00 Simon Asika <notifications@github.com>:

> I can successfully install 2.0.5 in a new Joomla 3.5.0
> [image: banners_and_alerts_ _joomla_350_-_administration_-_icons]
> <https://cloud.githubusercontent.com/assets/1639206/14019487/fc479274-f20d-11e5-8f48-0217b2f3bd22.jpg>
>
> It seems you miss the windwalker library files, do you check the file
> permissions?
>
> Try directly install windwalker and re open AQI to test.
> Download:
> https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.1/lib_windwalker_2.1.zip
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lyrasoft/quickicons/issues/33#issuecomment-200858377>
>



-- 
FG
Gmail
