### ISSUE TITLE
Serialization of 'Closure' is not allowed 

### ISSUE THREAD

**Issue by tmumm** [lyrasoft/quickicons#37]
I'm getting a fatal error when accessing the component -  "Serialization of 'Closure' is not allowed"
Joomla debug traces to:
…/­vendor/­windwalker/­cache/­DataHandler/­SerializeHandler.php: 27

**Comment by juankadiaz** [comment]
yes, I have the same issue.

**Comment by asika32764** [comment]
What version of Joomla do you use?

**Comment by tmumm** [comment]
I'm seeing it on every 3.5.1 site. Various servers, different php versions, 5.3, 5.4 and 5.5.

**Comment by asika32764** [comment]
I can't reproduce this issue, can I have a admin account to access your admin?

You can send account information to asika32764 [at] gmail.com

**Comment by asika32764** [comment]
@tmumm Thank you, I can confirm the reason. I'll fix it in the next release after about 1-2 days.

**Comment by tmumm** [comment]
Thank you!  The prompt attention is very much appreciated.

**Comment by davidjosue007** [comment]
I have the same issue with the 2.0.6 release,on joomla 3.5.1 site. Various servers, different php versions, 5.3, 5.4 and 5.5.

**Comment by asika32764** [comment]
Currently please install new windwalker framework to solve this problem
https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.1.5/windwalker-rad-2.1.5.zip

New AQI version will release later.

**Comment by asika32764** [comment]
Try this new released
https://github.com/lyrasoft/quickicons/releases/tag/2.0.7
