### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by fabricioventura** [lyrasoft/quickicons#38]
Hello!

After updating the panel updates Joomla can not access the component's control panel, it generates an error 500!

My version: 2.0.7
Joomla: 3.5.1

Thank you!

**Comment by asika32764** [comment]
Hi, which package did you update?

Windwalker library or Quickicons?

Can you still access extension installer manager?

**Comment by fabricioventura** [comment]
I think updated windwalker.

These are my versions.

Asikart QuickIcons 2.0.7
Asikart QuickIcons Module 2.0.5
windwalker 4.1.5

Yes, i access the extension installer manager.

**Comment by asika32764** [comment]
OK just download the correct package here and upload install it.
https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.1.5/windwalker-rad-2.1.5.zip

This issue is caused by a wrong file URL in earlier update server.

**Comment by fabricioventura** [comment]
WOW! 
Perfect!! 
Very Thanks!
