### ISSUE TITLE
Fatal error: Class 'Windwalker\DI\Container' not found 

### ISSUE THREAD

**Issue by micker** [lyrasoft/quickicons#39]
hello on last release i have error on load component
http://urlsite/administrator/index.php?option=com_akquickicons
Fatal error: Class 'Windwalker\DI\Container' not found in /home/lemouvem/public_html/libraries/windwalker/src/Windwalker.php on line 55
how to solve it ?

**Comment by micker** [comment]
no idea ? please

**Comment by asika32764** [comment]
Please check `libraries/windwalker/src/DI/Container.php` exists or not.

And try re-install windwalker framework package
https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.1.5/windwalker-rad-2.1.5.zip

**Comment by micker** [comment]
yes after update windwlaker that works

**Comment by asika32764** [comment]
Since it worked, close this issue.

I think it is maybe some files missing when installing component.

**Comment by iamrobert** [comment]
Hi Asika,

The bug still exists with:
https://github.com/ventoviro/windwalker-joomla-rad/tree/master
installling 2.1.5 fixed the issue

**Comment by asika32764** [comment]
Which platform do you use?

I must check the reason is OS issue or not.

**Comment by iamrobert** [comment]
Maybe its just localhost as am using:

http://www.uniformserver.com/

with php 7




Robert Stark
Web + Graphic Designer
http://www.iamrobert.com
0918 44 88 24 || (04) 2706 5003
